site_name: Singularity Tutorial and Workshop
theme:
  name: readthedocs

nav:
  - Build an Apptainer image: index.md
  - Set up a Lua module: HowToSetUpAModule.md
  - A Makefile based approach: AMakefileBasedApproach.md
  - The ImageSmith: RunThroughImageSmith.md
